name: feature-ci

on:
  push:
    branches:
      - "feature/**"
  pull_request:
    branches:
      - dev

jobs:
  lint:
    name: lint
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Lint
        run: ./gradlew lint

  test:
    name: lint
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Tests
        run: ./gradlew test

  build:
    name: build
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v4

      - name: Build project
        run: ./gradlew build
